# Develop override settings

url: http://localhost:4000

# SEO Related / SEO-Tags
webmaster_verifications:
  google: false
  bing: false
  alexa:  false
  yandex: false

analytics:
  provider: false

sass:
  style: expanded